### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by PeytonTale** [non-reai/Gimkit-Hacks#13]
Yeah nice one , when i extracted it I immediately got a warning from Windows saying there was a threat, It had a trojan in it , Be careful.

**Comment by eris-webserv** [comment]
:clown:

the thing is open source. it literally just saves the websocket. even a CHILD could figure that out. THIS THING AIN'T EVEN OBFUSCATED.

windows is notorious for false flagging

**Comment by PierceMichael** [comment]
> Yeah nice one , when i extracted it I immediately got a warning from Windows saying there was a threat, It had a trojan in it , Be careful.

What did u do?

**Comment by eris-webserv** [comment]
Also, I'd like to be clear: I just tested this.

Gimkit is a failure.

**Comment by PierceMichael** [comment]
> Yeah nice one , when i extracted it I immediately got a warning from Windows saying there was a threat, It had a trojan in it , Be careful.

You got the warning cus windows detected it as a cheat/hack that's why

**Comment by non-reai** [comment]
what the fuck are you on

**Comment by non-reai** [comment]
this is funny imma keep this open

**Comment by non-reai** [comment]
also what the hell did you extract? theres nothing to extract.

**Comment by PierceMichael** [comment]
> also what the hell did you extract? theres nothing to extract.

I think they downloaded it for some reason

**Comment by non-reai** [comment]
im gonna add my discord here on the readme.md
