### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by PierceMichael** [non-reai/Gimkit-Hacks#14]
It doesn't seem to work rn

**Comment by TheLazySquid** [comment]
I've done some digging, and Gimkit recently added this at the bottom of one of the files:
```js
Object.freeze && (Object.freeze(JSON),
Object.freeze(Array)),
Object.defineProperty(window, "WebSocket", {
    configurable: !1,
    writable: !1
}),
Object.freeze(window.WebSocket.prototype);
```
This prevents this code from being able to mess with ```WebSocket.prototype.send```, which doesn't have any easy fix I can think of.

**Comment by non-reai** [comment]
huh.

**Comment by non-reai** [comment]
ok so im thinking we just create a new object similar to websockets.prototype and override that.

**Comment by non-reai** [comment]
didnt work

**Comment by PierceMichael** [comment]
Here's what each line of code is doing:

1.) Object.freeze is a method that makes an object immutable, meaning its properties cannot be added, deleted, or modified. Here, Object.freeze(JSON) is making the JSON object immutable.

2.) Object.freeze(Array) is making the Array object immutable.

3.) Object.defineProperty is a method for defining new properties on an object or modifying existing ones. Here, the code is defining the "WebSocket" property on the "window" object with certain attributes. configurable: !1 means the property cannot be deleted or modified, writable: !1 means the value cannot be changed.

4.) Object.freeze(window.WebSocket.prototype) is making the prototype of the WebSocket object immutable, meaning its properties cannot be modified.

Overall, this code is trying to ensure that certain objects and properties cannot be changed.

**Comment by PierceMichael** [comment]
So we can't use WebSocket

**Comment by non-reai** [comment]
so what could we do

we could go old fashion route (buggy as heck but why not)

**Comment by non-reai** [comment]
solution is quite simple actually, you just have to make the script a bookmarklet and fire it before the page loads (and the object is frozen.)

**Comment by PierceMichael** [comment]
So when I press enter after typing in the website I also click the bookmarklet

**Comment by non-reai** [comment]
yea before the page loads (when the page is still white)
