### ISSUE TITLE
Too Fast

### ISSUE THREAD

**Issue by Crosshairs2** [non-reai/Gimkit-Hacks#15]
Can you tell me what page to refresh on? Also, it says refresh and try again every time. please tell me what i'm doing wrong.

**Comment by PierceMichael** [comment]
so when you refresh a page it goes white before the page loads whats when you want to start it
Do it before you enter the pin to join

**Comment by non-reai** [comment]
lmao read the readme

**Comment by Crosshairs2** [comment]
Thanks it worked!
