### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by PierceMichael** [non-reai/Gimkit-Hacks#2]
It seems to not be working for me It just highlight what my mouse is over red, nothing else

**Comment by non-reai** [comment]
all this does is log the question so the next time you get the questions it only shows the answer.

**Comment by PierceMichael** [comment]
it doesn't do that for me

**Comment by non-reai** [comment]
im going to rewrite this stuff anyways

**Comment by non-reai** [comment]
@PierceMichael i have a newer hack, look at readme before using.

**Comment by non-reai** [comment]
https://github.com/non-reai/Gimkit-Hacks/blob/main/thenewerandcoolerhack(beta).js

**Comment by PierceMichael** [comment]
ok I'll try it later

**Comment by PierceMichael** [comment]
it works but only for games that have a money system. ex it doesn't work on snowbrawl. also cant hold u or get kicked for answering too quick. thx for this tho

**Comment by PierceMichael** [comment]
The new update works for all games. Thank you!!! 😊👍
