### ISSUE TITLE
look at bottom

### ISSUE THREAD

**Issue by rhino42811** [non-reai/Gimkit-Hacks#21]
so on homework i get a qustion wrong can i get out of the link or am I screwed

**Comment by non-reai** [comment]
huh?

**Comment by PierceMichael** [comment]
> so on homework i get a qustion wrong can i get out of the link or am I screwed

elaborate

**Comment by rhino42811** [comment]
so like on homework I will get a qution wrong and then try to exit out of the tab and when I get back in then I get one right  and press ; u it gives nothing and it doesn't take its away

**Comment by non-reai** [comment]
hw doesnt work yet
