### ISSUE TITLE
(This isn't really a issue) Could you add an auto feature? 

### ISSUE THREAD

**Issue by aedion1234** [non-reai/Gimkit-Hacks#23]
Do you think you could add an auto answer feature, I know that it used to be one there but not anymore but I think having an auto answer is good because I FREAKING GET KICKED SO MANY TIMES IN CLASSIC, so PLEASE. It shouldn't be that hard anyway (idk how hard 🤔)

**Comment by non-reai** [comment]
i thought nobody used it lmao

**Comment by non-reai** [comment]
added it, press u to toggle
