### ISSUE TITLE
Bookmarklet doesn't execute on Gimkit.com 

### ISSUE THREAD

**Issue by aedion1234** [non-reai/Gimkit-Hacks#24]
When I click on the bookmarklet on gimkit.com nothing happens, it was working just a few hours ago, now its not (It works on other sites, like the bookmarklet pops up, so javascript it not blocked on my computer)

**Comment by non-reai** [comment]
they patched it

solution: between step 1 & 2 type 'javascript:prompt()' into the url bar and hit enter and ok (your screen should go white)
