### ISSUE TITLE
It doesn’t work.

### ISSUE THREAD

**Issue by TheRealSoftmap** [non-reai/Gimkit-Hacks#25]
I tried this out on my devices, nothing works. Can you please fix?

Thanks,
Softmap.

**Comment by non-reai** [comment]
what game mode

**Comment by TheRealSoftmap** [comment]
Gimkit Classic.

**Comment by non-reai** [comment]
i just tested it and it works. what browser are you using?

**Comment by TheRealSoftmap** [comment]
I’m using Apple Safari, on iPadOS 16.4.1.

**Comment by non-reai** [comment]
im pretty sure it only works on desktop chrome

**Comment by TheRealSoftmap** [comment]
Thanks for the info! I will try that out soon! I will let you know if it works on Chrome for iPad! Can you also make a version that uses bookmarks like Minesraft2‘s Blooket Cheats?

**Comment by non-reai** [comment]
you can use this alr use thiss as a bookmark

type 'javascript:' and paste the script in a bookmark

**Comment by Danno6776** [comment]
Hi I am just asking to make Blooket cheats like GitHubman6996  pls

**Comment by non-reai** [comment]
nah bro ive retired out of the business yk what i mean
