### ISSUE TITLE
How did schools find out about JS?

### ISSUE THREAD

**Issue by WisePeopleIs** [non-reai/Gimkit-Hacks#30]
My school has JS unblocked but the hacks dont work

**Comment by non-reai** [comment]
what game mode

only ones that work reliably is those non-2d games

2d might work

**Comment by WisePeopleIs** [comment]
i tried to use it in super rich mode but it did not work and i tried in multiple other non 2d game modes but it still did not work.

**Comment by non-reai** [comment]
it does work, i just tested it. Provide more info (browser, what you're doing, etc)

**Comment by WisePeopleIs** [comment]
I am using Bing but my school chromebook is set to chrome. I am saving it as a bookmark and i click it when in game and it does not work it does not say "Saved" or "You can use the hacks"

**Comment by non-reai** [comment]
what does it prompt you with when you put it in? can you check the console for any errors?

**Comment by WisePeopleIs** [comment]
How do you check the console?

**Comment by non-reai** [comment]
ctrl shift I or f12

**Comment by WisePeopleIs** [comment]
no hacks work anymore

**Comment by WisePeopleIs** [comment]
In the console it says nothing happened and plus every game has improved their security so i am now closing this issue and I wont return to github unless there is a new script that comes out and work on gimkit, and blooket.

**Comment by non-reai** [comment]
blud it literally works there is a video that came out on it a week ago (check README.md)
