### ISSUE TITLE
all games patched hacks.

### ISSUE THREAD

**Issue by WisePeopleIs** [non-reai/Gimkit-Hacks#31]
There's no game that you can hack, and most people who post on here are people on Chromebooks or in school. This means once a school has blocked any type of scripting, the person who made the project is forced to not update their project. And if they still update, like Minesraft2, they will get terminated and the only people who go on to this website are people in school trying to get hacks or unblocker for their computer. What I am trying to say is that you can't basically hack any game unless you have your own personal computer. So now there will be fake hacks that don't work put into this website. 

It was nice hacking but all things come to an end.

**Comment by non-reai** [comment]
what is blud yapping on about!!

**Comment by WisePeopleIs** [comment]
ok lil bro

**Comment by non-reai** [comment]
says the one that doesn't know how to use a script which there are literal step by step instructions in the README.md

**Comment by non-reai** [comment]
or you're on a Chromebook and atp what's the point in commenting this issue on my repo ☠

seems more like a you problem than a me problem.
