### ISSUE TITLE
Capture the flag

### ISSUE THREAD

**Issue by PierceMichael** [non-reai/Gimkit-Hacks#5]
It doesn't work on capture the flag
But does seem to work on everything else

**Comment by non-reai** [comment]
for any of those gimkits that you can walk around, press ";" while still in the answering menu.

**Comment by PierceMichael** [comment]
Ok thx

**Comment by thehackermasn** [comment]
The script doesnt work anymore

**Comment by PierceMichael** [comment]
> The script doesnt work anymore

Yea it doesn't work anymore
